// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PuppetHandle : RemoteTableHandle<EventContext, Puppet>
        {
            protected override string RemoteTableName => "puppet";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Puppet row) => row.EntityId;

                public EntityIdUniqueIndex(PuppetHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class PlayerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Puppet row) => row.PlayerId;

                public PlayerIdIndex(PuppetHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal PuppetHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Puppet row) => row.EntityId;
        }

        public readonly PuppetHandle Puppet;
    }
}
