// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CraftSnowBallHandler(ReducerEventContext ctx, uint playerId);
        public event CraftSnowBallHandler? OnCraftSnowBall;

        public void CraftSnowBall(uint playerId)
        {
            conn.InternalCallReducer(new Reducer.CraftSnowBall(playerId), this.SetCallReducerFlags.CraftSnowBallFlags);
        }

        public bool InvokeCraftSnowBall(ReducerEventContext ctx, Reducer.CraftSnowBall args)
        {
            if (OnCraftSnowBall == null) return false;
            OnCraftSnowBall(
                ctx,
                args.PlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CraftSnowBall : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public uint PlayerId;

            public CraftSnowBall(uint PlayerId)
            {
                this.PlayerId = PlayerId;
            }

            public CraftSnowBall()
            {
            }

            string IReducerArgs.ReducerName => "CraftSnowBall";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CraftSnowBallFlags;
        public void CraftSnowBall(CallReducerFlags flags) => CraftSnowBallFlags = flags;
    }
}
