// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveSnowBallHandler(ReducerEventContext ctx, MoveSnowBallTimer timer);
        public event MoveSnowBallHandler? OnMoveSnowBall;

        public void MoveSnowBall(MoveSnowBallTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveSnowBall(timer), this.SetCallReducerFlags.MoveSnowBallFlags);
        }

        public bool InvokeMoveSnowBall(ReducerEventContext ctx, Reducer.MoveSnowBall args)
        {
            if (OnMoveSnowBall == null) return false;
            OnMoveSnowBall(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveSnowBall : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveSnowBallTimer Timer;

            public MoveSnowBall(MoveSnowBallTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveSnowBall()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "MoveSnowBall";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveSnowBallFlags;
        public void MoveSnowBall(CallReducerFlags flags) => MoveSnowBallFlags = flags;
    }
}
