// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnDelayedSnowballHandler(ReducerEventContext ctx, DelayedSnowball delayed);
        public event SpawnDelayedSnowballHandler? OnSpawnDelayedSnowball;

        public void SpawnDelayedSnowball(DelayedSnowball delayed)
        {
            conn.InternalCallReducer(new Reducer.SpawnDelayedSnowball(delayed), this.SetCallReducerFlags.SpawnDelayedSnowballFlags);
        }

        public bool InvokeSpawnDelayedSnowball(ReducerEventContext ctx, Reducer.SpawnDelayedSnowball args)
        {
            if (OnSpawnDelayedSnowball == null) return false;
            OnSpawnDelayedSnowball(
                ctx,
                args.Delayed
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnDelayedSnowball : Reducer, IReducerArgs
        {
            [DataMember(Name = "delayed")]
            public DelayedSnowball Delayed;

            public SpawnDelayedSnowball(DelayedSnowball Delayed)
            {
                this.Delayed = Delayed;
            }

            public SpawnDelayedSnowball()
            {
                this.Delayed = new();
            }

            string IReducerArgs.ReducerName => "SpawnDelayedSnowball";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnDelayedSnowballFlags;
        public void SpawnDelayedSnowball(CallReducerFlags flags) => SpawnDelayedSnowballFlags = flags;
    }
}
