// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerInputHandler(ReducerEventContext ctx, DbVector2 direction, float rotation);
        public event UpdatePlayerInputHandler? OnUpdatePlayerInput;

        public void UpdatePlayerInput(DbVector2 direction, float rotation)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerInput(direction, rotation), this.SetCallReducerFlags.UpdatePlayerInputFlags);
        }

        public bool InvokeUpdatePlayerInput(ReducerEventContext ctx, Reducer.UpdatePlayerInput args)
        {
            if (OnUpdatePlayerInput == null) return false;
            OnUpdatePlayerInput(
                ctx,
                args.Direction,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerInput : Reducer, IReducerArgs
        {
            [DataMember(Name = "direction")]
            public DbVector2 Direction;
            [DataMember(Name = "rotation")]
            public float Rotation;

            public UpdatePlayerInput(
                DbVector2 Direction,
                float Rotation
            )
            {
                this.Direction = Direction;
                this.Rotation = Rotation;
            }

            public UpdatePlayerInput()
            {
                this.Direction = new();
            }

            string IReducerArgs.ReducerName => "UpdatePlayerInput";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePlayerInputFlags;
        public void UpdatePlayerInput(CallReducerFlags flags) => UpdatePlayerInputFlags = flags;
    }
}
