// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DelayedSnowball
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "position")]
        public DbVector2 Position;

        public DelayedSnowball(
            ulong Id,
            SpacetimeDB.ScheduleAt ScheduledAt,
            uint PlayerId,
            DbVector2 Position
        )
        {
            this.Id = Id;
            this.ScheduledAt = ScheduledAt;
            this.PlayerId = PlayerId;
            this.Position = Position;
        }

        public DelayedSnowball()
        {
            this.ScheduledAt = null!;
            this.Position = new();
        }
    }
}
