// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Obstacle
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "obstacle_id")]
        public string ObstacleId;
        [DataMember(Name = "collider_type")]
        public ColliderType ColliderType;
        [DataMember(Name = "box_size")]
        public DbVector2 BoxSize;
        [DataMember(Name = "sphere_radius")]
        public float SphereRadius;

        public Obstacle(
            uint EntityId,
            string ObstacleId,
            ColliderType ColliderType,
            DbVector2 BoxSize,
            float SphereRadius
        )
        {
            this.EntityId = EntityId;
            this.ObstacleId = ObstacleId;
            this.ColliderType = ColliderType;
            this.BoxSize = BoxSize;
            this.SphereRadius = SphereRadius;
        }

        public Obstacle()
        {
            this.ObstacleId = "";
            this.BoxSize = new();
        }
    }
}
