// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SnowBall
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "direction")]
        public DbVector2 Direction;
        [DataMember(Name = "speed")]
        public float Speed;

        public SnowBall(
            uint EntityId,
            uint PlayerId,
            DbVector2 Direction,
            float Speed
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Direction = Direction;
            this.Speed = Speed;
        }

        public SnowBall()
        {
            this.Direction = new();
        }
    }
}
